services:
    wordpress:
        build:
            context: .
            target: php
        environment:
            WORDPRESS_DB_HOST: db
            WORDPRESS_DB_USER: wordpress
            WORDPRESS_DB_PASSWORD: wordpress
            WORDPRESS_DB_NAME: wordpress

        volumes:
            - wordpress_data:/var/www/html
            - ./plugins/wpnation-boilerplate:/var/www/html/wp-content/plugins/wpnation-boilerplate
            - exclude_node_modules:/var/www/html/wp-content/plugins/wpnation-boilerplate/node_modules
            - exclude_php_vendor:/var/www/html/wp-content/plugins/wpnation-boilerplate/vendor
        depends_on:
            - db

    db:
        image: mariadb:latest
        environment:
            MYSQL_DATABASE: wordpress
            MYSQL_USER: wordpress
            MYSQL_PASSWORD: wordpress
            MYSQL_ROOT_PASSWORD: rootpassword
        volumes:
            - db_data:/var/lib/mysql
    nginx:
        image: nginx
        ports:
            - "80:80"
        volumes:
            - ./config/nginx.conf:/etc/nginx/conf.d/default.conf:ro
            - wordpress_data:/var/www/html
            - ./plugins/wpnation-boilerplate:/var/www/html/wp-content/plugins/wpnation-boilerplate
            - exclude_php_vendor:/var/www/html/wp-content/plugins/wpnation-boilerplate/vendor

        depends_on:
            - wordpress

    webpack:
        build:
            context: .
            target: node
        working_dir: /var/www/html/wp-content/plugins/wpnation-boilerplate
        volumes:
            - wordpress_data:/var/www/html
            - ./plugins/wpnation-boilerplate:/var/www/html/wp-content/plugins/wpnation-boilerplate
            - exclude_node_modules:/var/www/html/wp-content/plugins/wpnation-boilerplate/node_modules
        environment:
            - WATCHPACK_POLLING=true
        command: bash -c "yarn install && yarn run start"
        ports:
            - "3000:3000"
            - "3001:3001"
        depends_on:
            - wordpress

volumes:
    db_data:
    wordpress_data:
    exclude_node_modules:
    exclude_php_vendor:
